Objetivo0
mariavallejo20/proyecto_mvo pull request #1
Opened 2022-09-19 11:12 UTC by mariavallejo20

2022-09-20 11:16 UTC, JJ commented
Si no pones la lista de comprobación, no sé si has comprobado que lo que envías es correcto.

2022-09-20 11:17 UTC, mariavallejo20 commented
#Lista de comprobación 
* [x] ¿Se trata de un problema real del que se tenga conocimiento personal?
* [x] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
* [x] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
* [x] ¿Se ha incluido la configuración del repositorio y se ha enlazado desde el `README`?

#Objetivos de configuración
* [x] Creación de par de claves y subida de clave pública a GitHub.
* [x] Configuración correcta del nombre y correo electrónico (mariavallejo20@correo.ugr.es)
* [x] Edición del perfil en GitHub
* [x] Creación de la rama para el objetivo 0
* [x] Creación del pull request para el objetivo 0

2022-09-20 11:19 UTC, JJ requested changes
No entiendo bien el problema. Pero hay varios temas aparte
1. ¿Quién va a introducir los productos recomendados?
2. ¿Qué tipo de lógica de negocio se va a aplicar para los productos recomendados? ¿Va más allá de la búsqueda? (Uno de los items de la lista de comprobación).

2022-09-20 11:19 UTC, JJ commented on README.md
> +Además de esto, podría aparecer una sección con los productos más utilizados o
Si pones "además de" es que no estás entendiendo bien el problema.

2022-09-20 11:42 UTC, mariavallejo20 commented
@JJ ya puede revisar la lógica de negocio :)

2022-09-20 11:50 UTC, JJ commented
¿La respuesta a esta pregunta es positiva?

> ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?

También: la lógica de negocio no es sólo lo que se vende. Mira también [qué constituye una lógica de negocio aceptable](http://jj.github.io/IV/documentos/proyecto/0.Repositorio#descripci%C3%B3n)

2022-09-20 11:59 UTC, mariavallejo20 commented
Si, ya que la idea no es tener una base de datos llena de productos y que el cliente busque en esta, si no que la idea es que a partir de una serie de criterios se determine el tipo de piel del cliente y se cree una rutina facial, con los productos a utilizar, orden en el que deben aplicarse o la metodología de aplicación. Es decir, no se trata de un buscador de productos sin más, si no de un recomendador de la rutina completa.

2022-09-20 15:08 UTC, mariavallejo20 commented
@JJ puede revisar mi respuesta

2022-09-20 15:19 UTC, JJ commented
> Si, ya que la idea no es tener una base de datos llena de productos y que el cliente busque en esta, si no que la idea es que a partir de una serie de criterios se determine el tipo de piel del cliente y se cree una rutina facial, con los productos a utilizar, orden en el que deben aplicarse o la metodología de aplicación. Es decir, no se trata de un buscador de productos sin más, si no de un recomendador de la rutina completa.

Por favor, mira de nuevo qué es y qué no una lógica de negocio aceptable. Si hay algún algoritmo que tú conozcas que combine las entradas y dé las salidas, podría serlo. Quedaría el problema (serio) de tener el catálogo de productos y extraer de ellos lo que use la lógica de negocio (que no sé cómo lo solucionarás, porque *no* puedes pedir al usuario que los introduzca). Por eso os he dicho desde el principio que trabajéis con problemas realistas, y realistas quiere decir que no confiéis en que alguien vaya a teclear todos los datos necesarios para resolverlo.

2022-09-20 16:35 UTC, mariavallejo20 commented
@JJ le he dado un nuevo enfoque al proyecto, partiendo de la misma base, pero creo que ahora si he explicado mejor la lógica de negocio.

2022-09-20 18:14 UTC, JJ commented
> # Lista de comprobación
> 
>     * [x]  ¿Se trata de un problema real del que se tenga conocimiento personal?
> 
>     * [x]  ¿Se trata de un problema que para solucionar requiera el despliegue
>       de una aplicación en la nube?
> 
>     * [x]  ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
>       solucionarse sólo almacenando y buscando?
> 
>     * [x]  ¿Se ha incluido la configuración del repositorio y se ha enlazado desde el `README`?

Voy a suponer que lo que has puesto debajo responde a esta pregunta, pero desde luego no lo has enlazado desde el README.

2022-09-20 18:19 UTC, JJ requested changes
Debéis entender que este es un proyecto que vais a ir programando. Que tenéis que validar (punto 2 de una metodología) y que tenéis que desarrollar de forma incremental. A partir de eso y lo que te  comento, puedes acercarte un poco mejor a la solución.

2022-09-20 18:19 UTC, JJ commented on README.md
> +para mejorar la estética y eliminar por completo las impurezas y células muertas. Tras una limpieza profesional es indispensable mantener la higiene de la piel con una buena rutina facial, adecuada a
¿Cuál es el problema? ¿Los esteticistas no crean ahora esas rutinas? ¿No son personalizadas? ¿Tienen que calcular mucho tiempo algún aspecto parcial?

2022-09-20 18:19 UTC, JJ commented on README.md
> +observadas por el/la estecisita, como pueden ser la existencia de puntos negros, granos, ausencia de brillo, irritaciones, etc. se cree una rutina facial personalizada con los productos que mejor se
Sigues sin especificar qué tipo de cálculo hay que hacer para este tipo de operación. Recuerda lo que pone en la plantilla. ¿Se trata de buscar una rutina con tres o cuatro criterios de búsqueda? Si lo es, no es adecuada para la asignatura. Lo sería si esa rutina hubiera que generarla a partir de una base usando algún tipo de operación matemática relativamente compleja.

2022-09-20 18:19 UTC, JJ commented on README.md
> +El objetivo principal de este proyecto, será minimizar el tiempo que emplea el experto en crear
¿Cuanto tarda ahora? ¿Por qué tarda tanto tiempo? Si entiendes eso (que es empatizar con la clienta) empezarás a entender cuál es el problema y ayudar a solucionarlo.

2022-09-22 18:03 UTC, JJ requested changes
Está bien que hayas buscado una base de datos real con la que trabajar. Desgraciadamente, falla la fase de empatía porque no parece que abordes ningún problema real, ni parece que haya una lógica de negocio detrás.
Se me ocurre que una posibilidad sería correlacionar esa base de datos con otra; por ejemplo, ingresos en UCI o gastos presupuestarios (cada cosa que se gaste tiene que estar en un portal de transparencia). O quién organiza esos festejos. Fusionar dos bases de datos si tiene lógica de negocio, ya que tienes que ser capaz de encontrar un gasto que corresponda a un evento.
Y si correlacionamos la empresa que organiza el evento con el signo político del Ayuntamiento, podríamos llevarnos alguna sorpresa... 

Pero es simplemente un ejemplo en el que veas que fusionar datos procedentes de varias fuentes sí puede ser interesante de por si.

2022-09-22 20:07 UTC, mariavallejo20 commented
@JJ Me imagino que la base de datos sobre los presupuestos puedo encontrarla en el portal de transparencia de la Junta de Andalucía, sin embargo, no se donde podría encontrar la empresa que organiza el evento. 
Por otro lado, me surge la siguiente duda; ¿La aplicación se basaría en relacionar, por ejemplo, la base de datos de los eventos con los presupuestos o la empresa y la visualización de esta correlación?

2022-09-23 05:18 UTC, JJ commented
> @JJ Me imagino que la base de datos sobre los presupuestos puedo encontrarla en el portal de transparencia de la Junta de Andalucía, sin embargo, no se donde podría encontrar la empresa que organiza el evento.
> Por otro lado, me surge la siguiente duda; ¿La aplicación se basaría en relacionar, por ejemplo, la base de datos de los eventos con los presupuestos o la empresa y la visualización de esta correlación?

Sería encontrar esa correlación, por fechas, nombres de empresas (que pueden no ser exactamente iguales). Los eventos puede que no hayan sido pagados del presupuesto de la Junta, sino de otro lugar.

2022-09-23 07:41 UTC, mariavallejo20 commented
@JJ Disculpa tanto cambio con la idea del proyecto pero me gustaría encontrar algo que realmente me guste. He modificado el readme con una nueva idea para ver si esta es más acertada.

2022-09-23 11:13 UTC, JJ commented
> @JJ Disculpa tanto cambio con la idea del proyecto pero me gustaría encontrar algo que realmente me guste. He modificado el readme con una nueva idea para ver si esta es más acertada.

Puedes hacer todos los cambios que desees, faltaría más.

2022-09-23 11:27 UTC, JJ requested changes
Como yo cocino, te cuento un poco como lo hago
* Normalmente pienso lo que voy a cocinar con un día o varios de antelación, sobre todo si requieren marinado o poner en agua alguna cosa.
* Si me encuentro que tengo que cocinar en el día, tardo en ir a la frutería a comprar verduras una media hora. Si es al Mercadona, mínimo 45 minutos. Si la receta tarda x (desde 10 minutos un alio ed olio ed pepperoncino a 3 horas un chile con carne o una boloñesa), se le añade ese tiempo. Y en función de eso, decido.
* Normalmente siempre hay ajo, guindilla y queso granapadano o similar para solucionar un aglio ed olio ed pepperoncino. Cacciopepe es todavía más simple: queso y pimienta. Pero si hay que cocinar, o hago algo complicado para el que tengo todos los ingredientes, o algo más simple si tengo que ir a comprar algún ingrediente. 

Con esto te digo que, empatizando (hablando con la gente que tiene ese problema, o examinando realmente qué se hace en estos casos) puedes perfilar y definir más el problema, y también crear una lógica de negocio que sea realmente útil. Ánimo, ya te queda menos.

2022-09-23 11:27 UTC, JJ commented on README.md
> +El principal problema es la dificultad que tiene una persona a la hora de decidir que cocinar, sobre todo teniendo en cuenta los
Ya el título no se corresponde.

2022-09-23 11:27 UTC, JJ commented on README.md
> +ingredientes de los que se dispone o otras comidas realizadas en el día.
Como cocinero de la familia con bastante frecuencia, este problema se da raramente, porque normalmente se piensa en la comida el día antes o incluso la semana antes, si se hacen compras semanales. Pero entiendo que pueda haber diferentes historias de usuario.

2022-09-23 11:27 UTC, JJ commented on README.md
> +La solución planteada será crear una aplicación que permita al usuario marcas sus ingredientes y recetas favoritas o que ya hayan probado y deseen repetir en otro momento, y a partir de estos datos s
Estás cambiando el contexto del problema o incluso el problema en si. Los gustos no aparecen en la descripción del problema, ni los "ingredientes frecuentes" (ni los has definido). 
Tampoco dejas clara la lógica de negocio. "Priorizar" puede serlo siempre que se siga una heurística relativamente compleja, que tendrías que poner (¿Maximizar los ingredientes que sí hay disponibles? ¿Minimizar el tiempo necesario para preparar la receta?). Si logras representar en un vector todas las características de un plato (de todos los que tengas almacenados) y calcular una distancia normalizada y ordenar según distancia, podría ser. Si metes una heurística del tipo que minimice el tiempo necesario en cocinar + comprar los componentes necesarios, pidiéndole a la usuaria que diga aproximadamente cuanto tardaría en ir a comprar un conjunto de ingredientes), podría hasta estar bien. Pero por favor piénsatelo en función de lo que realmente te interese o quieras hacer.
Si no, es un simple ejercicio de búsqueda.

2022-09-26 14:10 UTC, mariavallejo20 commented on README.md
> +La solución planteada será crear una aplicación que permita al usuario marcas sus ingredientes y recetas favoritas o que ya hayan probado y deseen repetir en otro momento, y a partir de estos datos s
Mi idea se acerca más a priorizar aquellas recetas que maximicen el número de ingredientes disponibles o minimicen el tiempo necesario para preparar la receta, no se cual de las dos es una mejor lógica de negocio o si podrían ser las dos y que el usuario elija si desea maximizar los ingredientes o minimizar el tiempo de preparación. 
No me modificado el readme hasta entender bien si mi idea es acertada. 
@JJ

2022-09-26 15:35 UTC, JJ commented on README.md
> +La solución planteada será crear una aplicación que permita al usuario marcas sus ingredientes y recetas favoritas o que ya hayan probado y deseen repetir en otro momento, y a partir de estos datos s
Maximizar y minimizar son problemas de optimización, pero tal como lo formulas no corresponde al problema original. Por favor, formúlalo correctamente y explica claramente la lógica de negocio que vas a usar.

2022-09-26 16:25 UTC, mariavallejo20 commented
@JJ formulé de nuevo el problema y la solución, espero haber expresado bien la lógica de negocio esta vez. Espero su corrección.
Gracias :)

2022-09-29 10:41 UTC, mariavallejo20 commented
@JJ he incluido la configuración del repositorio y la he enlazado al readme.

2022-09-29 15:26 UTC, JJ commented
OK, pero ya estaba aprobado, puedes fusionar cuando quieras.

2022-09-30 07:14 UTC, merged