[IV-22-23] Objetivo 2 de @martahuetem sobre el repositorio de @mariavallejo20
mariavallejo20/proyecto_mvo pull request #11
Opened 2022-10-27 11:04 UTC by martahuetem

**Sobre la estructura del repositorio**
* [ ] ¿He seguido las mejores prácticas en nombre de las clases y ficheros y
   disposición de los mismos?
**Sobre el análisis del problema**
* [ ] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo
   que se ha creado?
* [ ] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor,
   una entidad o un agregado?
* [ ] ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo
   objeto valor que no dependa de ningún otro (y que sea la base de muchos
   otros)?
**Sobre la planificación y la programación**
* [ ] ¿Los issues representan un problema, y no una tarea?
* [ ] ¿Todos los mensajes de commit explican el cambio, y no se
      limitan a repetir el nombre del fichero que se ha cambiado?
* [ ] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
* [ ] ¿Se ha hecho una revisión real del código para comprobar que todos
   los atributos y funciones creadas están respaldadas por una HU?
* [ ] ¿Todos los issues creados están asignados a una HU?
* [ ] ¿Todos los cambios en el código están asignados a un issue al que se
      referencia en un commit? Los issues sobre los que estoy trabajando, ¿han
      sido asignados al primer milestone?
* [ ] ¿Se ha asignado al mismo milestone el PR que se ha hecho?
* [ ] ¿Son los milestones sobre los que estoy trabajando productos
   mínimamente viables? ¿O tengo que solicitar al product manager que
   cree milestones adicionales o precise de qué producto se trata?

2022-10-27 11:09 UTC, martahuetem commented
Hola @mariavallejo20!! Acabo de subir los archivos. ¿Qué te parece? 
Ahora me dices 💗

2022-10-27 11:15 UTC, mariavallejo20 commented on enum/unidades
> +    kilogramo: "kilogramo",
Hola @martahuetem!! El enumerado me parece genial, sin embargo, atendiendo a la base de datos creo que también podríamos añadir el "gramo" como una unidad.

2022-10-27 11:16 UTC, mariavallejo20 requested changes
Échale un vistazo a lo que te he comentado, por lo demás, creo que está bastante bien. Gracias 💜

2022-10-27 11:18 UTC, martahuetem commented on enum/unidades
> +    kilogramo: "kilogramo",
Hola @mariavallejo20!! Ahora mismo lo añado!!

2022-10-27 11:19 UTC, martahuetem reviewed
Listo @mariavallejo20 !!

2022-10-27 11:19 UTC, martahuetem commented on enum/unidades
> +    kilogramo: "kilogramo",
Listo!!

2022-10-27 11:21 UTC, mariavallejo20 approved these changes
De acuerdo, por mi parte todo correcto!! 💜🤩

2022-10-27 11:22 UTC, martahuetem commented
Hola @mariavallejo20!!! Perfecto!! Lo entrego ya! 🥰🥰

2022-10-28 09:18 UTC, martahuetem commented
@JJ solicito revisión

2022-10-28 09:57 UTC, JJ requested changes
Revisa, por favor
* Objetivos de aprendizaje de esta semana y la anterior
* Guión de este objetivo
* Errores frecuentes tanto esta semana como la anterior.

En general, en esta asignatura nos centramos en que el estudiante aprenda una metodología, no que ponga un resultado. Es esa metodología la que hay que seguir para superar el objetivo.

2022-10-28 09:57 UTC, JJ commented on iv.yaml
> -objeto valor: [./src/ingrediente.js, ./src/receta.js, ./src/user.js]
:thinking:

2022-10-28 09:57 UTC, JJ commented on src/coleccion.js
> +class Coleccion{
Este cambio no sigue ningún issue, por lo que es imposible saber si es correcto o no.

2022-10-28 09:57 UTC, JJ commented on enum/unidades
> +const Unidades = {
"Subida de los archivos" no es un mensaje de commit aceptable. Los mensajes de commit forman parte de la metodología de trabajo.

2022-10-28 10:17 UTC, martahuetem commented on src/coleccion.js
> +class Coleccion{
@JJ es un cambio relacionado con el issue #8.

2022-10-28 10:17 UTC, martahuetem commented on iv.yaml
> -objeto valor: [./src/ingrediente.js, ./src/receta.js, ./src/user.js]
Lo cambié porque lo comenté con María en clase.

2022-10-28 10:18 UTC, martahuetem commented on enum/unidades
> +const Unidades = {
Lo tendré en cuenta para los siguientes.

2022-10-28 10:21 UTC, martahuetem commented
@JJ he cambiado los errores que he visto. Solicito revisión.

2022-10-28 10:22 UTC, JJ commented on src/coleccion.js
> +class Coleccion{
Y eso es lo que tienes que poner en el mensaje de commit.

2022-10-28 10:23 UTC, JJ commented on enum/unidades
> +const Unidades = {
> @JJ he cambiado los errores que he visto. Solicito revisión.

No has cambiado nada, no has hecho ningún commit desde la revisión.

2022-10-28 10:55 UTC, mariavallejo20 commented on src/coleccion.js
> +class Coleccion{
Hola @martahuetem, he visto que como habíamos comentado has cambiado el nombre de la clase a "Coleccion".

2022-10-28 10:55 UTC, mariavallejo20 approved these changes

2022-10-30 15:09 UTC, martahuetem commented
@JJ solicito revisión.

2022-10-30 16:51 UTC, JJ commented
Revisión ¿de qué? Sigue habiendo los mismos 8 commits que hace 3 días, el último de los cuales es [2e0f3cf](https://github.com/mariavallejo20/proyecto_mvo/pull/11/commits/2e0f3cfd134d38aacc85641dbf1bb2e8216b6b86)
¿Hemos entendido que si no se ha desarrollado correctamente el código ni siquiera se puede decir que es incorrecto? ¿Y que hay que desarrollar el código siguiendo un procedimiento específico?

2022-10-30 16:52 UTC, JJ commented
> Revisa, por favor
> 
>     * Objetivos de aprendizaje de esta semana y la anterior
> 
>     * Guión de este objetivo
> 
>     * Errores frecuentes tanto esta semana como la anterior.
> 
> 
> En general, en esta asignatura nos centramos en que el estudiante aprenda una metodología, no que ponga un resultado. Es esa metodología la que hay que seguir para superar el objetivo.

Por si no queda claro, cambiar cosas para que el código que se ha desarrollado mal ahora parezca que está bien no es esa metodología.

2022-10-31 13:38 UTC, mariavallejo20 approved these changes
Hola @martahuetem, he echado un vistazo a los cambios que has hecho en los ficheros en función a lo que hemos hablado en los distintos issues y por mi parte creo que está todo correcto.
Gracias por tu trabajo. 🤗💜

2022-11-02 20:06 UTC, martahuetem commented
@JJ solicito revisión

2022-11-03 06:29 UTC, JJ commented
Los mensajes de commit no pueden repetir lo que es evidente que se ha hecho en el commit, como modificación de un fichero o creación de una clase. Deben explicar por qué se ha optado por esa solución.

2022-11-03 08:20 UTC, martahuetem commented
@JJ solicito revisión

2022-11-03 10:14 UTC, JJ commented
Ni [2b75584](https://github.com/mariavallejo20/proyecto_mvo/pull/11/commits/2b75584c9bd0e0b061b0d4030cf17f237ba1e8cc) ni [500aed0](https://github.com/mariavallejo20/proyecto_mvo/pull/11/commits/500aed0493138e790a7d965f9b616abda8bc17bb) siguen las buenas prácticas en mensaje de commit: la primera línea tiene más de 50 caracteres.

2022-11-03 10:21 UTC, martahuetem commented
> Ni [2b75584](https://github.com/mariavallejo20/proyecto_mvo/pull/11/commits/2b75584c9bd0e0b061b0d4030cf17f237ba1e8cc) ni [500aed0](https://github.com/mariavallejo20/proyecto_mvo/pull/11/commits/500aed0493138e790a7d965f9b616abda8bc17bb) siguen las buenas prácticas en mensaje de commit: la primera línea tiene más de 50 caracteres.

Vale, lo tendré en cuenta en los siguientes.

2022-11-03 13:10 UTC, martahuetem commented
Hola @mariavallejo20! Ya he hecho todos los cambios que he visto necesarios para adaptarme a tu #6. ¿Qué te parece? 
Espero tu respuesta para pedir la revisión. 💙💙

2022-11-03 13:13 UTC, mariavallejo20 approved these changes
Vale @martahuetem!! Por mi parte me parece bien, gracias por tu trabajo. 😇🤗

2022-11-03 13:13 UTC, martahuetem commented
@JJ solicito revisión.

2022-11-03 18:01 UTC, martahuetem commented
@JJ solicito revisión

2022-11-03 19:10 UTC, JJ approved these changes
Se ha seguido el procedimiento correcto. El resultado puede ser más o menos discutible, pero no me toca a mi discutirlo :+1:

2022-11-04 08:09 UTC, merged