Objetivo1
mariavallejo20/proyecto_mvo pull request #2
Opened 2022-09-29 11:56 UTC by mariavallejo20

2022-10-06 11:31 UTC, mariavallejo20 commented
@JJ listo para revisión :)

2022-10-06 18:38 UTC, JJ requested changes
Aparte de lo comentado, no entiendo muy bien por qué vuelves a meter las claves y eso en el objetivo 1. ¿No estaban ya fusionados a main?

2022-10-06 18:38 UTC, JJ commented on README.md
> +El principal problema es la dificultad que tiene una persona a la hora de decidir que cocinar, sobre todo teniendo en cuenta los ingredientes de los que se dispone o la cantidad de tiempo del que se
No entiendo muy bien. ¿Por qué modificas esto de nuevo?

2022-10-06 18:38 UTC, JJ commented on docs/historias_usuario.md
> +#[[HU1] Francisco quiere prepararle a sus hijos recetas con sus ingredientes favoritos.](https://github.com/mariavallejo20/proyecto_mvo/issues/4)
¿"favoritos" no sería igual a "gustos"? ¿Qué diferencia habría?

2022-10-06 18:38 UTC, JJ commented on docs/milestones.md
> +## [[M0] Estructura de datos para almacenar recetas.](https://github.com/mariavallejo20/proyecto_mvo/milestone/1)
Lo hemos hablado esta mañana. Una estructura de datos no es un producto. Por favor, revisa el resto de los milestones de la misma forma.

2022-10-07 07:19 UTC, mariavallejo20 commented
No he modificado el objetivo 0, esto ya está fusionado en el main, sin embargo, cuando cree la rama e hice el PR, no había cerrado el PR de la rama 0 por que, aunque ya me había aceptado el objetivo 0 le había añadido un comentario para indicarle que había añadido la configuración antes de cerrar el PR. Creo que ese es el motivo de que aparezcan esos cambios en este PR.

2022-10-07 07:32 UTC, mariavallejo20 commented
Listo para revisión :) @JJ

2022-10-07 08:51 UTC, JJ approved these changes
Voy a optar por aprobar, aunque deberías tener en cuenta los comentarios que te he hecho antes del siguiente objetivo o en este mismo PR. No hace falta que solicites revisión doe nuevo.

2022-10-07 08:51 UTC, JJ commented on docs/milestones.md
> +## [[M1] Fichero que contiene la estructura de datos para representar las recetas recomendadas.](https://github.com/mariavallejo20/proyecto_mvo/milestone/2)
¿Seguro que la secuencia es correcta? ¿No necesitarás la lógica de negocio antes?
En todo caso, tampoco tienes que hacer los productos tan atómicos. Posiblemente el diseño de todas las estructuras de datos tengas que hacerlo a la vez.

2022-10-09 15:56 UTC, merged