[IV-22-23] Objetivo3
mariavallejo20/proyecto_mvo pull request #25
Opened 2022-11-03 08:54 UTC by mariavallejo20

# Lista de comprobación
* [ ]  ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [ ]  ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [ ]  ¿Ese issue está asignado a un milestone?
* [ ] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [ ]  ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [ ]  ¿El PR, que también es un issue, está asignado al mismo milestone?
* [ ] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes?

2022-11-03 21:14 UTC, mariavallejo20 commented
@JJ listo para revisión, gracias. 😊

2022-11-07 11:01 UTC, mariavallejo20 commented
He mejorado la documentación y criterios de elección del gestor de dependencias y el task runner. Además, he solucionado algunos conflictos que habían surgido al fusionar el objetivo 2.
Listo para su revisión, gracias. @JJ 😁

2022-11-07 16:39 UTC, JJ requested changes
Por favor, consulta [estos errores frecuentes](https://github.com/JJ/IV-22-23/blob/master/sesiones/semana-08.md#objetivo-3) y los de esta semana.

2022-11-07 16:39 UTC, JJ commented on docs/gestor_dependencias.md
> +La gestión de dependencias es el proceso de automatización de la instalación, actualización, configuración y eliminación de las dependencias necesarias.
Esta frase no aporta nada. No me cuentes lo que es un gestor de dependencias, eso ya lo sé. Dime qué criterios vas a usar para elegir uno u otro.

2022-11-07 18:16 UTC, mariavallejo20 commented on docs/gestor_dependencias.md
> +La gestión de dependencias es el proceso de automatización de la instalación, actualización, configuración y eliminación de las dependencias necesarias.
He eliminado esa frase. Los criterios que he utilizado para la elección del gestor de dependencias están un poco más abajo en el apartado "Criterios a seguir para la elección". ¿Debería colocar esa sección al principio?

2022-11-07 18:52 UTC, JJ commented on docs/gestor_dependencias.md
> +La gestión de dependencias es el proceso de automatización de la instalación, actualización, configuración y eliminación de las dependencias necesarias.
Me da igual donde la coloques. No se trata de que escribáis una cosa u otra. Se trata de que *efectivamente* establezcáis unos criterios y los sigáis para elegir una herramienta (esta y las que sigan).

2022-11-07 21:24 UTC, mariavallejo20 commented on docs/gestor_dependencias.md
> +La gestión de dependencias es el proceso de automatización de la instalación, actualización, configuración y eliminación de las dependencias necesarias.
De acuerdo, pero entonces ,¿lo que he hecho es correcto?. Es decir, establecer una criterios y posteriormente elegir una herramienta en función a estos. ¿Habría que mejorar algo? Gracias por su ayuda.🤗

2022-11-08 06:43 UTC, JJ commented on docs/gestor_dependencias.md
> +La gestión de dependencias es el proceso de automatización de la instalación, actualización, configuración y eliminación de las dependencias necesarias.
Si no has establecido unos criterios objetivos de antemano para elegir las herramientas y seguido esos criterios para elegirlas, no, no es correcto. Te recuerdo [los errores frecuentes en este objetivo](https://github.com/JJ/IV-22-23/blob/master/sesiones/semana-08.md#objetivo-3)

2022-11-08 15:14 UTC, mariavallejo20 commented on docs/gestor_dependencias.md
> +La gestión de dependencias es el proceso de automatización de la instalación, actualización, configuración y eliminación de las dependencias necesarias.
He intentado expresar mejor los criterios que he seguido, cuantos de ellos cumplen cada gestor y cual ha sido mi elección final. ¿Puede decirme si es correcto ahora? Muchas gracias. @JJ 🤗

2022-11-08 16:17 UTC, JJ commented on docs/gestor_dependencias.md
> -La gestión de dependencias es el proceso de automatización de la instalación, actualización, configuración y eliminación de las dependencias necesarias.
¿Qué problema tienes con poner exactamente lo que has hecho? "Borro descripción considerada innecesaria en revisión #25"

2022-11-08 16:20 UTC, JJ commented on docs/gestor_dependencias.md
> +1. Estructura del proyecto: Una de las mejores prácticas es la buena estructura, se debe dividir cada proyecto en archivos, carpetas y subcarpeta de forma correcta.
No tiene nada que ver con el gestor de dependencias.

2022-11-08 16:21 UTC, JJ commented on docs/gestor_dependencias.md
> +2. Lenguaje en el que esté basado el gestor: La mejor opción será emplear un gestor que esté basado en NodeJS.
¿Por qué? ¿deno o bun que están escritos en Rust o zig no sirven para gestionar dependencias entonces?

2022-11-08 16:21 UTC, JJ commented on docs/gestor_dependencias.md
> +3. Para seguir una buena práctica es recomendable utilizar el fichero de dependencias “package.json”.
No es una opción, es un prerrequisito. Es estándar.

2022-11-08 16:21 UTC, JJ commented on docs/gestor_dependencias.md
> +4. Que se trate de una herramienta fácil de utilizar y aprender, para así minimizar el tiempo de aprendizaje.
¿Cómo mides esto objetivamente?

2022-11-08 16:22 UTC, JJ commented on docs/gestor_dependencias.md
> +    - En Node.JS el código se encuentra estructurado por módulos, que a medida que vamos trabajando iremos necesitando agregar más de estos según sea el caso y es en este punto donde justamente entra
?? No entiendo esto, de verdad. Ni qué tiene que ver.

2022-11-08 16:23 UTC, JJ commented on docs/gestor_dependencias.md
> +    - Una parte importante de esta herramienta es conocer los 2 ficheros principales:
No es de esta herramienta. ¿No hemos quedado en que era un prerrequisito para elegir el gestor de dependencias?

2022-11-08 16:24 UTC, JJ commented on docs/gestor_dependencias.md
> +    - Para realizar el seguimiento de los paquetes emplea un archivo denominado "bower.json". Esto implica que NO se cumple el criterio 3.
No usa el package.json que tú misma has puesto como prerrequisito.
Llegado a este punto, no creo que realmente deba seguir corrigiendo.

2022-11-09 06:17 UTC, JJ commented on docs/gestor_dependencias.md
> +La gestión de dependencias es el proceso de automatización de la instalación, actualización, configuración y eliminación de las dependencias necesarias.
Lo habrá sido si efectivamente has seguido esos criterios para la elección y no simplemente has escrito cosas para pasar el objetivo y justificar lo que ya tenías elegido de antemano.

2022-11-10 15:48 UTC, mariavallejo20 commented
Buenas tardes @JJ!🤗 He modificado los criterios y la elección del gestor de dependencias, así como la del task runner, con lo que creo que se adecua más a la explicación de esta mañana. Listo para revisión, gracias.😇

2022-11-10 19:09 UTC, JJ commented
Por favor, intentad que la primera línea del commit tenga sólo 50 caracteres.

2022-11-10 19:14 UTC, JJ requested changes
Por favor, no incluyas herramientas que no corresponden a lo que se solicita (un gestor de dependencias) ni a los criterios que tú has establecido. Bower no es un gestor de dependencias, es un [*package manager **for the web** *](https://bower.io/). Mira lo que dice en la misma página:
![Captura de pantalla de 2022-11-10 20-13-53](https://user-images.githubusercontent.com/500/201185777-fdaa1564-4db5-45c1-b842-8326037da493.png)
por si fuera poco. Por favor, leed atentamente qué es lo que estáis sugiriendo y para qué sirve, y también si está vigente o no.

2022-11-10 19:14 UTC, JJ commented on docs/gestor_dependencias.md
> +    - La instalación de paquetes no es demasiado rápida, sin embargo, teniendo en cuenta el tamaño de mi proyecto y la cantidad de dependencias que tendrá, este no será un gran inconveniente.
Si no están relacionado con los criterios, no lo pongáis.

2022-11-10 19:14 UTC, JJ commented on docs/gestor_dependencias.md
> +    - Para la gestión de dependencias emplea el archivo "boxer.json", lo que no cumple con la práctica extendida por la mayoría de los desarrolladores. Esto puede provocar deuda técnica en un futuro,
Te vuelvo a decir lo mismo. No es un gestor de dependencias, ni cumple con los requisitos que has puesto. No deberías ponerlo.

2022-11-10 19:14 UTC, JJ commented on docs/gestor_dependencias.md
> +    - Yarn instala las dependencias en paralelo permitiéndote agregar múltiples archivos simultáneamente, lo que aumenta la velocidad de instalación de las dependencias. Sin embargo, teniendo en cuen
Si no está relacionado con los criterios, *no lo pongáis*

2022-11-10 19:14 UTC, JJ commented on docs/gestor_dependencias.md
> +Por otro lado, entre PNPM y Yarn, he decidido escoger PNPM, ya que ambas tienes características similares que cumplen los criterios establecidos, buen soporte y documentación, pero PNPM presenta una
typo:velocidad

2022-11-10 22:28 UTC, mariavallejo20 commented
Tendré en cuenta el tamaño en los siguientes commit.

2022-11-10 22:31 UTC, mariavallejo20 commented
He eliminado Bower y lo que no estaba relacionado con los criterios que he establecido. Listo para revisión. Gracias. 🕵️‍♂️🤗

2022-11-11 06:36 UTC, JJ approved these changes
👍 salvo detalles. Por favor, corrige antes del siguiente objetivo

2022-11-11 06:36 UTC, JJ commented on Makefile
> +	node --check ./src/usuario.js
Debería comprobar *todos* los ficheros, los que estén y los que no

2022-11-11 06:36 UTC, JJ commented on docs/gestor_dependencias.md
> +* **NPM (Node Package Manager)**:
No se escribe en mayúsculas nunca

2022-11-11 06:36 UTC, JJ commented on package.json
> +  "main": "index.js",
No usas ningún main.

2022-11-11 08:24 UTC, merged