[IV-22-23] Objetivo 4
mariavallejo20/proyecto_mvo pull request #33
Opened 2022-11-17 12:35 UTC by mariavallejo20

# Lista de comprobación
* [ ]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [ ]  ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se
   esté desarrollando?
* [ ]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [ ]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [ ]  ¿Se han documentado las elecciones de biblioteca de aserciones y del
   de *test runner*?
* [ ] ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y
test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo
`unittest` como *test runner* y `pytest` como biblioteca de aserciones?
* [ ] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [ ]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [ ]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?
* [ ] ¿Se han testeado también las excepciones?

2022-12-01 13:26 UTC, mariavallejo20 commented
Listo para revisión @JJ!! 😇😁

2022-12-02 09:42 UTC, mariavallejo20 commented
Listo para revisión @JJ!! 😇😁

2022-12-02 16:03 UTC, mariavallejo20 commented
Listo para revisión @JJ!! 😇😁

2022-12-02 19:14 UTC, JJ requested changes
Como ya os dije, tenéis que comprobar la lógica de negocio. No parece que estés comprobando nada en este, más bien borrando cosas que no necesitas. Por favor, intentad que realmente se implemente un algoritmo, y no un simple bucle que haga una búsqueda; os dije explícitamente en el objetivo 0 que esto no se consideraba lógica de negocio.

2022-12-02 19:14 UTC, JJ commented on docs/test_runner.md
> +* En primer lugar, descarto Jasmine ya que no es compatible con el formato estándar TAP.
No parece que sea así. Es un test runner y está descrito como tal, y lo de TAP va de suyo.

2022-12-02 19:14 UTC, JJ commented on docs/test_runner.md
> +* En segundo lugar, descarto Jest, ya que no me permite elegir una biblioteca de aserciones al contar con la suya propia. Aunque esto podría ser una ventaja a la hora de incluir todo en el test runne
¿Y qué más te da? Tiene su propia biblioteca de aserciones, reduce la deuda técnica y las dependencias directas.
Si ya tuvieras un proyecto y ya hubieras elegido una biblioteca de aserciones, esto podría ser un problema, ya que podrían usar las mismas funciones y ser incompatibles. Pero no parece que sea un requisito realista.

2022-12-02 19:14 UTC, JJ commented on src/usuario.js
> +    getEmail(){
No sé muy bien como ha pasado esto. No hay ninguna HU que pida el email. Ya puesta, podías haberlo borrado también.

2022-12-05 20:57 UTC, mariavallejo20 commented on src/ingrediente.js
> +    constructor(nombre, id_ingrediente){
He eliminado la ID de esta clase, por que pensando en lo que me ha dicho realmente podemos identificar cada ingrediente con su nombre, ya que cada ingrediente es único y no hay 2 con el mismo nombre.

2022-12-05 21:01 UTC, mariavallejo20 commented on src/usuario.js
> +    getEmail(){
Se añadió el email como forma de identificación de cada usuario, ya que el nombre podría no se único ¿Debería eliminarlo? 🤔

2022-12-05 21:01 UTC, mariavallejo20 commented on src/ingrediente.js
> -     getTiempoPlancha(){
Si, me dí cuenta

2022-12-06 10:48 UTC, mariavallejo20 commented on docs/aserciones.md
> +Atendiendo a las bibliotecas de aserciones que se pueden extraer de la [documentación de mocha]( https://mochajs.org/#assertions) tenemos:
He añadido también "assert" como posible elección ya que he encontrado que también es popular, sin embargo, me he decantado por seguir utilizando chai ya que creo que es la mejor elección. 😁

2022-12-13 20:32 UTC, mariavallejo20 commented
Finalmente, como he indicado en el issue #36 he empleado el algoritmo de Greedy adaptado a mis necesidades para implementar la lógica de negocio, como habíamos hablado.
Además de eso, he corregido lo que me comentó en la anterior revisión.
Listo para revisión @JJ !! 😁🥳

2022-12-14 07:19 UTC, JJ requested changes
El principal problema es que has hecho *algo* para tratar de superar este objetivo, en concreto con el `package.json`, que echa por tierra el resto del trabajo que hayas podido hacer. Por favor, intenta resolver autónomamente los problemas que se te puedan plantear a todos los niveles, porque no hacerlo así lleva a errores bastante profundos como el que se evidencia en este fichero.

2022-12-14 07:19 UTC, JJ commented on docs/aserciones.md
> +* **Assert:**
Esta no es la biblioteca assert estándar. Por favor, tratad de esforzaros un poco en buscar las bibliotecas (y herramientas en general) que se usan.

2022-12-14 07:19 UTC, JJ commented on docs/aserciones.md
> +Tras documentarme sobre las diferentes bibliotecas de aserciones y una vez establecidos los criterios que cumplen o no cada uno de ellos, **he decidido decantarme por Chai** ya que es la más extendid
No sé qué significa "extendida". Y no has evaluado objetivamente el "mantenimiento" de la misma, habiendo herramientas para ello (que he mencionado en clase varias veces).

2022-12-14 07:19 UTC, JJ commented on docs/test_runner.md
> +       - Debemos tener en cuenta que se aconseja con mayor frecuencia por los desarrolladores
Con mayor frecuencia, ¿dónde? Una vez más, deben usarse criterios objetivos.

2022-12-14 07:19 UTC, JJ commented on docs/test_runner.md
> +    - Este test runner soporta el formato TAP.
Si no lo hiciera no sería un test runner.

2022-12-14 07:19 UTC, JJ commented on docs/test_runner.md
> +       - Debemos tener en cuenta si cuenta con su propia librería de aserciones o podemos elegir la que queremos utilizar.
Si la librería de aserciones no usa el formato TAP, es que no es una buena librería de aserciones.

2022-12-14 07:19 UTC, JJ commented on docs/test_runner.md
> +    - Mocha cuenta con una gran documentación y una sintaxis sencilla y fácil de aprender, atendiendo a la experiencia de la mayoría de los desarrolladores.
La sintaxis que usa es la de JavaScript, como no podía ser de otra forma.
Por favor, no hagáis afirmaciones discutibles. Limitaros a exponer cómo cubre los requisitos, y qué puntuación tiene en los criterios objetivos que haya.

2022-12-14 07:19 UTC, JJ commented on docs/test_runner.md
> +Tras documentarme sobre los diferentes posibilidades y una vez establecidos los criterios he podido apreciar que cualquier test runner de los mencionados podría ser una buena opción. Para poder hacer
Esa comparativa compara las descargas. `jest` tiene *el triple* que `mocha`. También tiene el doble de estrellas. Por favor, sed consecuentes con los criterios objetivos que vosotros mismos habéis elegido.

2022-12-14 07:19 UTC, JJ commented on package.json
> +  "version": "0.4.0",
¿Por qué bajas la versión?

2022-12-14 07:19 UTC, JJ commented on package.json
> +  "license": "GNU General Public License v3.0",
¿Y cambias la licencia?

2022-12-14 07:19 UTC, JJ commented on package.json
> -    "pnpm": "^7.15.0"
¿Y eliminas `pnpm`, que era lo que habías elegido en #25?

2022-12-14 10:23 UTC, mariavallejo20 commented
He intentado corregir todo lo referente a los criterios y la elección de las herramientas, además de lo que hemos comentado sobre el gestor de dependencias. Listo para que le eches un vistazo @JJ 😇🤗

2022-12-14 10:54 UTC, JJ requested changes
No he entrado a fondo en la lógica de negocio, pero todavía la selección de herramientas tiene algunas deficiencias. Por favor, no uses "buenas prácticas" en un contexto en el que no encaja; trata de entender el concepto de "deuda técnica" (mira la presentación que hice al respecto) y sobre todo trata de establecer criterios objetivos y presentar opciones que realmente correspondan a lo que se va a elegir.

2022-12-14 10:54 UTC, JJ commented on docs/aserciones.md
> +      - Cuenta con recientes actualizaciones, buen mantenimiento y una comunidad activa, como podemos apreciar en su [repositorio de github]( https://github.com/chaijs/chai). Siendo su última actuali
Este enlace está mal.

2022-12-14 10:54 UTC, JJ commented on docs/aserciones.md
> +      - Tiene una comunidad poco activa como podemos ver (repositorio de github)[https://github.com/nodejs/node-core-test].
Este enlace tampoco usa markdown correcto.

2022-12-14 10:54 UTC, JJ commented on docs/aserciones.md
> +      - Tiene una comunidad poco activa como podemos ver (repositorio de github)[https://github.com/nodejs/node-core-test].
Ni es el enlace correcto. Literalmetne dice "user-land port of node:test" para que se pueda usar con versiones anteriores de node. Por favor, mirad lo que enlazáis antes de hacerlo.

2022-12-14 10:54 UTC, JJ commented on docs/aserciones.md
> +* **node:test:**
Por favor, mira la documentación. *No* es una biblioteca de aserciones.

2022-12-14 10:54 UTC, JJ commented on docs/aserciones.md
> +      - Se debe tener en cuenta los estilos de aserciones que permite la biblioteca.
Esto no tiene nada que ver con las buenas prácticas. El estilo de aserciones es una elección personal. Tienes que optar por uno u otro estilo para reducir las opciones posibles.

2022-12-14 10:54 UTC, JJ commented on docs/aserciones.md
> +2.	Mantenimiento de la biblioteca: Se deberá tener en cuenta la comunidad de la que dispone, ya que se busca tener un buen mantenimiento y actualización, disminuyendo la posibilidad de deuda técnica
La deuda técnica no sólo depende de la actualización; también del hecho de que haya que introducir herramientas adicionales, que habrá que mantener. Cuantas menos herramientas, menos deuda técnica.

2022-12-14 10:54 UTC, JJ commented on docs/test_runner.md
> +1.	Buenas prácticas:Debemos tener en cuenta si cuenta con su propia librería de aserciones o podemos elegir la que queremos utilizar.
Esto no tiene que ver con las buenas prácticas, tiene que ver con la deuda técnica.

2022-12-14 10:54 UTC, JJ commented on docs/test_runner.md
> +2.	Frescura del test runner: Se deberá tener en cuenta la comunidad de la que dispone el test runner, ya que se busca tener un buen mantenimiento y actualización, disminuyendo la posibilidad de deuda
"frescura" y "comunidad" son dos aspectos a tener en cuenta. Como te he comentado arriba, hay webs que te dan puntuaciones al respecto y permiten hacer comparaciones. Por favor, úsalas.

2022-12-14 10:54 UTC, JJ commented on package.json
> +    "test": "mocha"
Si estás usando `npm` como test runner, debes eliminar `make` en todos los sitios donde aparezca.

2022-12-14 10:54 UTC, JJ commented on src/usuario.js
> +    RecomendarRecetasTiempo(recetas)
Por favor, consulta y sigue las mejores prácticas en nombres de métodos en JavaScript.

2022-12-14 19:39 UTC, mariavallejo20 commented on docs/aserciones.md
> +      - Una de las principales desventajas de esta librería es su mantenimiento, ya que tiene pocas actualizaciones y una comunidad poco activa, como podemos apreciar en su [repositorio de github]( h
He utilizado [snyk](https://snyk.io/advisor/) para investigar sobre los diferentes criterios de mantenimiento, popularidad y seguridad de las diferentes posibilidades.

2022-12-14 19:41 UTC, mariavallejo20 commented on docs/test_runner.md
> +2.	Frescura del test runner: Se deberá tener en cuenta la comunidad de la que dispone el test runner, ya que se busca tener un buen mantenimiento y actualización, disminuyendo la posibilidad de deuda
He utilizado snyk para investigar sobre la frescura y comunidad de las diferentes opciones.

2022-12-14 19:54 UTC, mariavallejo20 commented on src/usuario.js
> +    RecomendarRecetasTiempo(recetas)
He consultado las convenciones sobre el nombrado de funciones en JavaScript, determinando que la mejora práctica es utilizar camelCase y sustantivos y verbos descriptivos.

2022-12-14 19:59 UTC, mariavallejo20 commented
He utilizado [snyk](https://snyk.io/advisor/) para comparar las diferentes puntuaciones sobre comunidad, seguridad y popularidad de las diferentes opciones de test runner y bibliotecas de aserciones como me ha indicado en los comentarios anteriores.
Además, he refactorizado el código utilizando camelCase para el nombrado de las funciones, siguiendo las mejores prácticas de js.
Listo para revisión @JJ!!

2022-12-15 06:16 UTC, JJ commented on docs/aserciones.md
> +      - Una de las principales desventajas de esta librería es su mantenimiento, ya que tiene pocas actualizaciones y una comunidad poco activa, como podemos apreciar en su [repositorio de github]( h
Enlázalo entonces y pon los resultados de Snyk Advisor.

2022-12-15 06:42 UTC, JJ requested changes
Aparte de los problemas indicados, el problema principal es que no estás implementando una lógica de negocio que vaya más allá de la búsqueda de una receta que se ajuste al tiempo necesario. Has quitado el tiempo que se necesitaba para preparar cada ingrediente, con lo que ahora mismo las recetas ni siquiera usan los ingredientes. 
Como siempre hemos dicho en esta asignatura, debes intentar plantearte de forma más precisa el problema que quieres resolver, y escribir los tests que prueben que has resuelto este problema. Tal como está ahora mismo (aparte de lo que se te ha indicado), el problema principal es que no se resuelven las HU correspondientes.

2022-12-15 06:42 UTC, JJ commented on docs/aserciones.md
> +Tras documentarme sobre las diferentes bibliotecas de aserciones y una vez establecidos los criterios que cumplen o no cada uno de ellos, **he decidido decantarme por Chai** ya que, es la más popular
No mencionas assert/test que es estándard en node desde la versión 18 (y se puede portar a versiones anteriores)

2022-12-15 06:42 UTC, JJ commented on docs/test_runner.md
> +Tras documentarme sobre los diferentes posibilidades y una vez establecidos los criterios he podido apreciar que cualquier test runner de los mencionados podría ser una buena opción, ya que todos cum
Usar lo que ya has usado es la definición de deuda técnica. Tampoco son tan diferentes las bibliotecas de aserciones; de hecho, `jest` usa `chai` por debajo, así que no habría que cambiar prácticamente nada. Y si cambias de mocha a ava lo único que hay que cambiar son los comandos del gestor de tareas.

2022-12-15 06:42 UTC, JJ commented on iv.yaml
>    fichero: Makefile
Si ya no usas esto, tendrás que cambiarlo o fallará a partir de ahora.

2022-12-15 06:42 UTC, JJ commented on package.json
> +    "chai": "^4.3.7"
Ya te lo dije ayer. Tienes que acostumbrarte a usar los comandos adecuados para añadir dependencias de desarrollo o producción a los ficheros de dependencias.

2022-12-15 06:42 UTC, JJ commented on src/ingrediente.js
> +     * @param {String} nombre // nombre del ingrediente (Identificará cada ingrediente)
Si se había modelizado el problema con todo lo anterior, no puedes simplemente borrarlo. Pero si lo borras (o haces cualquier otra cosa) también tienes que crear un issue. Y si la solución del issue implica que lo único que queda es el nombre, ni siquiera necesitas una clase para eso.

2022-12-15 06:42 UTC, JJ commented on src/receta.js
> +export default class Receta{
No entiendo por qué has eliminado las unidades, que se crearon para una historia de usuario determinada.

2022-12-15 06:42 UTC, JJ commented on src/usuario.js
>          return this.email;
¿Quitas las unidades de las recetas y dejas el email? ¿Te parece que eso es necesario para la lógica de negocio?

2022-12-15 06:42 UTC, JJ commented on src/usuario.js
> +        var mejorTiempo = 500
¿Esta constante qué issue para qué problema soluciona?

2022-12-15 06:42 UTC, JJ commented on src/usuario.js
> +        var mejorReceta = new Receta()
Las buenas prácticas de JS hoy en día desaconsejan el uso de `var`. Se usa `let` o `const`.

2022-12-15 06:42 UTC, JJ commented on src/usuario.js
> +        return mejorReceta;
Esto no lo puedes hacer.
Este bloque se está ejecutando una vez por cada elemento del array `recetas`. Por lo tanto, *en cada iteración* estás devolviendo el valor de la mejor receta `en esa iteración`. Como el resultado no lo asignas a nada, ese array está en contexto vacío, es decir, se tira. Pero por lo mismo no tienes que devolver nada.
Por otro lado, está simplemente devolviendo la receta con el tiempo mínimo. Creo que hay una función para eso.

2022-12-15 06:42 UTC, JJ commented on src/usuario.js
> +                this.recetas_propuestas.push(recetaSeleccionada)
Si esto es el resultado de una función, ¿por qué usas un atributo de objeto? ¿No te das cuenta de que así necesitas dos llamadas para obtener el resultado? (Y no tienes garantía de que se haya hecho otra llamada sobre el mismo objeto)

2022-12-15 06:42 UTC, JJ commented on test/test.js
> +        it('Se ha cargado correctamente', function(){
Los tests deben probar comportamientos.

2022-12-15 06:42 UTC, JJ commented on test/test.js
> +        it('El nombre del usuario NO puede ser una cadena vacía', function(){
Los tests deben probar la lógica de negocio, y el comportamiento que se busca en las historias de usuario. Este código ni siquiera debería existir.

2022-12-15 06:42 UTC, JJ commented on test/test.js
> +            var nombre = 'Maria Vallejo';
¿Ves como necesitas darle al programa datos que no necesita?

2022-12-15 06:42 UTC, JJ commented on test/test.js
> +            var receta2 = new Receta("Perrito Caliente", ['salchicha', 'pan'], 15);
Ni siquiera estás usando los ingredientes. Sólo el tiempo de elaboración de la receta.

2022-12-15 10:49 UTC, mariavallejo20 commented on iv.yaml
>    fichero: Makefile
He abierto un nuevo issue para solucionar este problema #40.

2022-12-15 10:52 UTC, mariavallejo20 commented on src/receta.js
> +export default class Receta{
Lo he quitado porque me he dado cuenta que el enumerado al que hace referencia no existe, ya que lo eliminó mi compañera en el objetivo 2.

2022-12-15 10:58 UTC, JJ commented on src/receta.js
> +export default class Receta{
No se trata de que exista o no. Se trata de si hace falta para avanzar la historia de usuario en la que se esté trabajando. En todo caso, si no es parte de este objetivo, os rogaría que los cambios correspondientes los hicierais *antes* del PR.

2022-12-15 11:04 UTC, mariavallejo20 commented on test/test.js
> +            var receta2 = new Receta("Perrito Caliente", ['salchicha', 'pan'], 15);
Como podemos ver en la HU3 #6 sobre el que estamos trabajando en este momento, debemos centrarnos en el tiempo de la receta, sin implicar los ingredientes, por ello, como me ha indicado no los utilizo y por tanto, no los pasaré ahora.

2022-12-15 11:11 UTC, mariavallejo20 commented on test/test.js
> +            var nombre = 'Maria Vallejo';
De la misma forma que los ingredientes, entiendo, que centrándonos en el HU3 #6 no es algo necesario, por tanto lo he eliminado

2022-12-15 12:40 UTC, mariavallejo20 commented
Listo para revisión!! ☺ @JJ

2022-12-15 12:43 UTC, mariavallejo20 commented
La lógica de negocio que he implementado, consiste primero en comprobar aquellas recetas que incluyen al menos un ingrediente de los disponibles del usuario. Una vez obtenidas estas recetas, recomendaremos al usuario aquellas que se adecuen al tiempo del que dispone, como he especificado en el issue #36

2022-12-16 06:41 UTC, JJ requested changes
El problema principal es la clave que se ha incluido en iv.yaml; el resto de las buenas prácticas sería también conveniente que las siguieras.

2022-12-16 06:41 UTC, JJ commented on iv.yaml
> +  orden: npm run all
Esta orden es incorrecta y te va a dar error en todos los objetivos sucesivos.

2022-12-16 06:41 UTC, JJ commented on iv.yaml
> +test: tests/test.js
¿Aquí pones un camino relativo sin `.` y arriba si?

2022-12-16 06:41 UTC, JJ commented on package.json
> +    "npm-run-all": "^4.1.5"
¿wait, what? ¿Por qué necesitas esto?

2022-12-16 06:41 UTC, JJ commented on src/usuario.js
>       getRecetasPropuestas(){
De veras, no hace falta tanto getter. Si se proponen recetas será lo que devuelva una función, no una variable de instancia.

2022-12-16 06:41 UTC, JJ commented on src/usuario.js
> +                if(encontrado != -1)
Agh, no, `-1` no, nunca. 
¿Por qué no usas para ingredientes una estructura de datos, como un conjunto, que te diga simplemente si pertenece o no? Así puedes usar un simple `filter` para filtrar las recetas que lo incluyan.

2022-12-16 06:41 UTC, JJ commented on src/usuario.js
> +    recomendarRecetas(recetas, Ingredientesdisponibles, tiempoDisponible)
¿Te parece que todo esto deba formar parte de una clase usuario? ¿O debería haber otra clase que manejara tanto los usuarios como las recetas?

2022-12-16 06:41 UTC, JJ commented on test/test.js
> +            let receta1 = new Receta("Huevo Frito", ["aceite", "huevo", "sal"], 10);
Esto es *arrange*. Debería hacerse *antes* de todos los tests.

2022-12-16 06:41 UTC, JJ commented on test/test.js
> +            nuevoUsuario.recomendarRecetas(recetasTotal, ["sal", "pimienta"], tiempoDisponible);
Estás haciendo dos peticiones para algo que sólo debería implicar una. No sé de dónde habéis sacado ese antipatrón, pero usar atributos de clase para depositar el resultado de una función no parece que sea la mejor práctica, ¿no te parece?

2022-12-16 10:46 UTC, mariavallejo20 commented on src/usuario.js
> +    recomendarRecetas(recetas, Ingredientesdisponibles, tiempoDisponible)
Desde mi punto de vista, creo que podría continuar implementando esto en la clase usuario, ya que estamos recomendando recetas para cada usuario concreto. Es cierto, que también se podría implementar en una clase independiente, pero no es algo que considere obligatorio, ya que como siempre hemos dicho no hay soluciones perfectas, simplemente unas diferentes a otras.

2022-12-16 11:00 UTC, mariavallejo20 commented
He resuelto los problemas que me ha comentado, listo para revisión @JJ! 🤗

2022-12-16 16:28 UTC, JJ commented on src/usuario.js
> +    recomendarRecetas(recetas, Ingredientesdisponibles, tiempoDisponible)
También he dicho que hay que buscar objetos valor inmutables. El que se implemente aquí o de forma independiente dependerá, fundamentalmente, de que los ingredientes sean fijos o variables. Si son fijos, necesita un objeto valor que los contenga y por tanto no debería ir aquí. Pero si son variables, no hay ninguna otra característica que defina al usuario: simplemente se tratará de una función que recibe varios ingredientes y devuelve un resultado. El "usuario" desaparece.

2022-12-16 16:33 UTC, JJ approved these changes
Creo que voy a optar por aprobar, aunque la clase usuario realmente no aporta ninguna funcionalidad que no se pueda incluir en una simple función. Hay que tratar siempre de hacer el producto más simple que consiga el efecto deseado.
En todo caso, puedes modificarlo antes del siguiente objetivo.

2022-12-16 16:33 UTC, JJ commented on docs/aserciones.md
> +* **node:assert:**
`node:assert` no funciona sin un "test runner" `node:test`. Deberías consultar la documentación, porque vienen los dos juntos. En concreto, `node:assert` no produce resultados en formato TAP.

2022-12-16 16:33 UTC, JJ commented on package.json
>    "directories": {
???

2022-12-16 16:33 UTC, JJ commented on src/usuario.js
> +    constructor(nombre, tiempo_disponible, recetas_propuestas){
¿Para qué necesitas el nombre del usuario?

2022-12-16 16:33 UTC, JJ commented on test/test.js
> +let receta5 = new Receta("Macarrones con nata", ["agua", "aceite", "sal", "pasta", "pimienta", "nata", "queso"], 30);
Los "viejos confiables" de la cocina estudiantil...

2022-12-16 16:33 UTC, JJ commented on test/test.js
> +let receta5 = new Receta("Macarrones con nata", ["agua", "aceite", "sal", "pasta", "pimienta", "nata", "queso"], 30);
(también: la pasta no debe ir *nunca* con nata. La cocina italiana no debe usar nata, nunca)

2022-12-16 18:06 UTC, merged