[IV-22-23] Objetivo 5
mariavallejo20/proyecto_mvo pull request #43
Opened 2023-01-02 12:03 UTC by mariavallejo20

# Lista de comprobación
* [ ] ¿Se han establecido criterios previos de elección de la imagen base, así
como los criterios de búsqueda que han conducido a las imágenes que se están
considerando?
* [ ] ¿Se ha tenido en cuenta que la imagen es para testear, y que por tanto tiene una función específica, tal como testear cómo va en la última versión publicada del lenguage?
* [ ] ¿Se ha tenido en cuenta que la versión de la imagen base sea la última?
* [ ] ¿Se han tenido en cuenta criterios reales para la elección, y no criterios irrelevantes como cuanto tiempo se tarda en construirla? (Se va a construir una vez, se va a usar cientos o miles de veces)
* [ ] ¿Se han seguido las buenas prácticas en las órdenes que construyen
   la imagen? ¿Especialmente las relativas a usuarios no privilegiados y demás?
* [ ] ¿La imagen incluye sólo y exclusivamente la infraestructura
   necesaria para pasar los tests? Por ejemplo, si se ha elegido la imagen
   "oficial" (lo que hay que hacer sólo en casos muy justificados) ¿se ha
   comprobado que lo que se instale sea sólo y exclusivamente lo necesario para
   nuestro proyecto?
* [ ] ¿Se han documentado y enlazado los commits a las imágenes que se
   han testeado?
* [ ] ¿Está establecido correctamente como `WORKDIR` el que se va a usar en los
   tests que se van a lanzar?
* [ ] ¿Se usa algún directorio adecuado para copiar contenidos del repositorio
en vez del directorio de trabajo?
* [ ] ¿Se han establecido claramente los criterios de búsqueda y de aceptación de
   la imagen base?
* [ ] ¿Tienes claro cuales son las condiciones en las que tiene que actualizarse
la imagen en DockerHub y has configurado el workflow de acuerdo con ello? En
particular, ¿sabes qué condiciones tienen que darse para que se actualice y qué
condiciones *no* deben darse?
* [ ] Si se usan GitHub actions para su publicación, ¿se han considerado
cuidadosamene los criterios (ramas, paths) para que se lancen?
* [ ] ¿Se ha comprobado que el ENTRYPOINT del contenedor no escriba nada en el
directorio que monta, ya que no tiene derecho de escritura?

2023-01-02 15:23 UTC, mariavallejo20 commented
Listo para revisión @JJ !! 😁

2023-01-03 11:02 UTC, JJ requested changes
Por favor, consulta los errores frecuentes correspondientes a este objetivo.

2023-01-03 11:16 UTC, mariavallejo20 commented
@JJ revisé los errores antes de entregar el objetivo, ¿me podría especificar un poco más donde está mi error? Por favor, es que no sé que debo mirar, gracias. 😅

2023-01-04 09:01 UTC, mariavallejo20 commented
* He eliminado los comentarios del dockerfile
* He definido como usuario el que creo sin permisos.
* No he quitado el "update" ya que considero que es necesario porque si no no encuentra el paquete npm a la hora de la instalación de este.
* He corregido una errata que he encontrado al repasar la elección de la imagen base.

He realizado estas correcciones aunque no se si me he dejado algo, puede echarle un vistazo @JJ

2023-01-04 09:08 UTC, JJ commented
> * He eliminado los comentarios del dockerfile
> 
>     * He definido como usuario el que creo sin permisos.
> 
>     * No he quitado el "update" ya que considero que es necesario porque si no no encuentra el paquete npm a la hora de la instalación de este.

No se trata de que lo quites o lo dejes. Se trata de que entiendas lo que hace, si hace falta de forma exclusiva sin ninguna otra opción y si se suele usar con alguna otra orden. Uno de los objetivos de aprendizaje relacionados con este es que entendáis las órdenes básicas de Linux y sepáis como usarlas, y es precisamente por que hace falta usarlas en este objetivo y el siguiente.

2023-01-04 09:13 UTC, JJ requested changes
El Dockerfile sigue sin seguir las buenas prácticas habituales y sin justificar adecuadamente la imagen base.

2023-01-04 09:13 UTC, JJ commented on Dockerfile
> +RUN groupadd -r group && useradd -r -g group user && chown -R user:group /app
¿No crees que sería conveniente hacer una mínima modificación del nombre de usuario, adaptado a este caso particular, después de copiarlo y pegarlo de algún ejemplo?

2023-01-06 14:05 UTC, mariavallejo20 commented
He investigado sobre las opciones de **update** y si realmente es necesario de forma exclusiva. Como he documentado en el issue #46, no he encontrado ninguna otra opción, ya que el problema que me encuentro, como especifico en el issue, es que de otra forma no me encuentra los paquetes.
¿Puede echarle un vistazo? @JJ Gracias.

2023-01-09 06:33 UTC, JJ commented
> He investigado sobre las opciones de **update** y si realmente es necesario de forma exclusiva. Como he documentado en el issue #46, no he encontrado ninguna otra opción, ya que el problema que me encuentro, como especifico en el issue, es que de otra forma no me encuentra los paquetes. ¿Puede echarle un vistazo? @JJ Gracias.

1. Se puede usar directamente desde uno de los comandos
2. Una vez que se usa update, es habitual también usar `upgrade` para las actualizaciones al sistema operativo desde la última publicación.

Uno de los objetivos de aprendizaje de las últimas semanas lectivas es revisar las prácticas habituales en el sistema operativo Linux. El mantener el sistema operativo del contenedor actualizado forma parte del mismo (como los permisos u otras cosas). O entender simplemente qué es lo que hace `update`, que es actualizar los índices con las últimas versiones de los paquetes, no "para que aparezca no sé qué cosa"; y si se hace para actualizar los índices a las útlimas versiones, es porque se quieren descargar esas últimas versiones, que pueden incluir actualizaciones de seguridad, por ejemplo. Una de las cuestiones básicas en Linux (y en cualquier SO) es mantenerlo actualizado. Esto debería hacerse *en cualquier contenedor*, pero mucho más si tu base es el sistema operativo, porque se entiende que ya habrán hecho este comando si usas una distribución "oficial"

En todo caso, eso no es problema principal para superar el objetivo.

2023-01-09 06:38 UTC, JJ requested changes
En la explicación que os hice en clase os incluí al menos tres clases diferentes de imágenes que se podían considerar, no sólo tres imágenes base de sistemas operativos. Te agradecería que al menos intentaras buscar cuales son *todas* las alternativas en este caso; por otro lado, los criterios y requisitos para elegir la imagen base deben usarse como lo que son, no simplemente para nombrarlos y no seguirlos.

2023-01-09 06:38 UTC, JJ commented on docs/imagen_base.md
> +Tras documentarme sobre las diferentes imágenes que podría utilizar, y decantarme, como he especificado antes por utilizar la de algún sistema operativo que me elimina cualquier funcionalidad que no
¿De qué forma los cumple? No es la que tiene menor peso, ni mucho menos.

2023-01-09 06:38 UTC, JJ commented on docs/imagen_base.md
> +    - Su peso es de 184 MB, algo mayor que los anteriores.
En concreto, más del doble que la de ubuntu y más de 20 veces mayor que la de Alpine. "Algo" igual no es la descripción más adecuada.

2023-01-09 13:07 UTC, mariavallejo20 commented on docs/imagen_base.md
> +Tras documentarme sobre las diferentes imágenes que podría utilizar, y decantarme, como he especificado antes por utilizar la de algún sistema operativo que me elimina cualquier funcionalidad que no
Sé que no es la que tiene menor peso. El criterio que he establecido no es escoger la imagen que tenga el menor peso, si no una imagen que tenga un peso reducido. He hecho esto así para no escoger "Alpine" ya que imagino que por su peso la habrán elegido otros compañeros y más de una vez me ha comentado que intente escoger otras cosas.
Pienso que "Ubuntu" no es una peor elección teniendo en cuenta que no tiene un peso muy alto, es decir, simplemente, es una solución diferente.

2023-01-09 13:19 UTC, mariavallejo20 commented
Listo para revisión @JJ

2023-01-09 13:58 UTC, mariavallejo20 commented
Listo para revisión @JJ

2023-01-10 07:04 UTC, JJ commented on docs/imagen_base.md
> +Tras documentarme sobre las diferentes imágenes que podría utilizar, y decantarme, como he especificado antes por utilizar la de algún sistema operativo que me elimina cualquier funcionalidad que no
Estás tratando de justificar por qué has elegido lo que has elegido, en vez de usar criterios objetivos que sirvan al proyecto. Si una imagen tiene 7 megas y otra 70, la que tiene 70 tarda 10 veces más en descargarse, punto. Las imágenes Docker es lo que se hace con ellas, descargarlas. 
En cuanto a lo de "no elegir lo de otros compañeros", es tan malo como elegir lo mismo, porque sigue indicando que se ha hecho el trabajo junto y simplemente se ha cambido algo en el último momento. Ya os expliqué en clase, repetidamente, que las posibilidades de elección de imagen base eran muy amplias, y pasaban por las imágenes del sistema operativo, imágenes del lenguaje oficiales, imágenes base de vendedores certificados, e imágenes base de cualquier persona que haya decidido hacerlas. También os indiqué que merecía la pena mirarlas, si no por elegirlas, por ver qué habían hecho y aprender a construir una imagen Docker para un fin determinado, *que es de lo que se trata este objetivo*.

2023-01-10 07:17 UTC, JJ requested changes
Sigue habiendo carencias tanto en la elección de la imagen base como en seguir las buenas prácticas para construir el contenedor en sí.

2023-01-10 07:17 UTC, JJ commented on .github/workflows/imagen_test.yml
> +        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
Si usas este hash para elegir la versión de la GitHub action, deberías justificarlo, aunque sea solamente para que vea que entiendes lo que estás haciendo. Aunque esta action no es parte del objetivo principal, siempre os he pedido que tratéis de entender lo que hacéis, y documentarlo os puede ayudar a entenderlo.

2023-01-10 07:17 UTC, JJ commented on Dockerfile
> +    apt-get install -y --no-install-recommends npm && npm install
Ejecuta sólo con privilegios aquellas acciones que lo necesiten, por favor.

2023-01-10 07:17 UTC, JJ commented on Dockerfile
> +COPY package.json /app
¿Seguro que esto copia todos los ficheros necesarios para construir la imagen Docker?

2023-01-10 07:17 UTC, JJ commented on docs/imagen_base.md
> +Tras echar un vistazo a algunas imágenes en el explorador de [DockerHub](https://hub.docker.com/search?q=) me he dado cuenta, que muchas de ellas incluyen muchas funcionalidades extra que no son para
Como te he indicado, hay otras imágenes base. No tienes más que buscarlas.

2023-01-10 07:17 UTC, JJ commented on docs/imagen_base.md
> +Finalmente, entre ubuntu y alpine, que son las mejores opciones en cuanto a los criterios deseados, he decidido decantarme por **ubuntu**, ya que aunque no es la de menor tamaño, cuenta con un peso b
¿Seguro que sólo tienes Ubuntu y Alpine?
Simplemente busca "minimalistic docker OS image" o similar y tendrás muchas alternativas. Incluso aunque elijas Ubuntu, tienes [esta alternativa](https://phusion.github.io/baseimage-docker/). Que no se trata de buscar lo mismo y al final elegir una cosa diferente por el hecho de hacerlo, se trata de llevar a cabo una pequeña búsqueda de alternativas *totalmente independiente* y tomar decisiones de forma totalmente independiente en base a esa búsqueda. Por ejemplo, simplemente buscar "best base image for node containers" o similar.

2023-01-10 14:38 UTC, mariavallejo20 commented on .github/workflows/imagen_test.yml
> +        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
He utilizado ese hash porque como he comentado en el issue #44 me basé en la documentación oficial de github sobre esto. Sin embargo, he estado investigando y he hecho algunas modificaciones cambiando el hash por las últimas versiones disponibles (v2 para la login-action y v3 para la build-push-action)

2023-01-10 18:48 UTC, mariavallejo20 commented on Dockerfile
> +COPY package.json /app
He añadido package-lock.json, pero he tenido problemas con esto que he documentado en el issue #48.

2023-01-10 18:49 UTC, mariavallejo20 commented
Listo para revisión @JJ

2023-01-10 19:28 UTC, JJ commented on .github/workflows/imagen_test.yml
> +        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
Por favor, la documentación que queréis que considere la ponéis en el PR. No puedo seguir todos los enlaces. ES razonable que uses la última versión, por eso te he dicho que lo mires.

2023-01-10 19:31 UTC, JJ approved these changes
Estoy impresionado.
No has elegido la herramienta con menos peso, pero realmente te lo has currado.

2023-01-10 19:31 UTC, JJ commented on Dockerfile
> +FROM phusion/baseimage:jammy-1.0.1
:clap:

2023-01-10 21:05 UTC, merged